### ISSUE TITLE
expected input_3 to have shape (15, 16) but got array with shape (10, 16)

### ISSUE THREAD

**Issue by tekeburak** [XifengGuo/CapsNet-Keras#54]
After I trained the model succesfully and run the following command on Google Colab.

`!python3 /content/drive/tut_competition/capsulenet_colab.py -t -w /content/result/trained_model.h5`

_keras version = 2.1.4
tensorflow version = 1.4.0_

**_I got this error:_**

2018-02-25 22:18:08.222033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
------------------------------Begin: manipulate------------------------------
Traceback (most recent call last):
  File "/content/drive/tut_competition/capsulenet_colab.py", line 278, in <module>
    manipulate_latent(manipulate_model, (x_test, y_test), args)
  File "/content/drive/tut_competition/capsulenet_colab.py", line 181, in manipulate_latent
    x_recon = model.predict([x, y, tmp])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1824, in predict
    check_batch_axis=False)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking : expected input_3 to have shape (15, 16) but got array with shape (10, 16)

**Comment by XifengGuo** [comment]
@tekeburak 
https://github.com/XifengGuo/CapsNet-Keras/blob/540f15dfc531c3e82f76fbae7de72bb9e48ae72a/capsulenet.py#L173

Change line#173 to `noise = np.zeros([1, 15, 16])`
