### ISSUE TITLE
ValueError: Error when checking input: expected input_2 to have shape (221,) but got array with shape (245,)

### ISSUE THREAD

**Issue by chikiuso** [XifengGuo/CapsNet-Keras#56]
Hi @XifengGuo, I got the following error when filling in my own dataset (in mnist ubyte format, but to 223 categories instead of 10) : 

Traceback (most recent call last):
  File "capsulenet.py", line 252, in <module>
    train(model=model, data=((x_train, y_train), (x_test, y_test)), args=args)
  File "capsulenet.py", line 138, in train
    callbacks=[log, tb, checkpoint, lr_decay])
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.3-py3.5.egg/keras/legacy/interfaces.py", line 91, in wrapper
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.3-py3.5.egg/keras/engine/training.py", line 2138, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.3-py3.5.egg/keras/engine/training.py", line 1428, in _standardize_user_data
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.3-py3.5.egg/keras/engine/training.py", line 120, in _standardize_input_data
ValueError: Error when checking input: expected input_2 to have shape (221,) but got array with shape (245,)

Do you have idea how to solve it? thanks!

Best Wishes,
Chi Kiu

**Comment by chikiuso** [comment]
I got it solved, it is because the compiling datasets in a wrong way, thanks!
