### ISSUE TITLE
Value Error for Cifar10 dataset

### ISSUE THREAD

**Issue by shrybht** [XifengGuo/CapsNet-Keras#87]
Hi 

I am getting the following error while running the Cifar10 dataset. Could you please help me with this?

`Traceback (most recent call last):
  File "capsulenet.py", line 264, in <module>
    train(model=model, data=((x_train, y_train), (x_test, y_test)), args=args)
  File "capsulenet.py", line 128, in train
    callbacks=[log, tb, checkpoint, lr_decay])
  File "C:\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Python\Python36\lib\site-packages\keras\engine\training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 140, in fit_generator
    val_x, val_y, val_sample_weight)
  File "C:\Python\Python36\lib\site-packages\keras\engine\training.py", line 802, in _standardize_user_data
    check_array_length_consistency(x, y, sample_weights)
  File "C:\Python\Python36\lib\site-packages\keras\engine\training_utils.py", line 227, in check_array_length_consistency
    str([x.shape for x in inputs]))

ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(30000, 32, 32, 1), (10000, 10)]`

**Comment by XifengGuo** [comment]
@shrybht It is obvious that you did not prepare the data correctly. Make sure `x_train.shape[0]==y_train.shape[0]` and `x_test.shape[0]==y_test.shape[0]`.

**Comment by bretthandrews** [comment]
@shrybht you may have already solved this issue, but I ran into the same problem. The fix requires changing the number of channels from `1` to `3` when reshaping `x_train` while modifying the `load_mnist` function to create a `load_cifar10` function. Here is my `load_cifar10` function:

```
def load_cifar10():
    from keras.datasets import cifar10
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()

    x_train = x_train.reshape(-1, 32, 32, 3).astype('float32') / 255.
    x_test = x_test.reshape(-1, 32, 32, 3).astype('float32') / 255.
    y_train = to_categorical(y_train.astype('float32'))
    y_test = to_categorical(y_test.astype('float32'))
    return (x_train, y_train), (x_test, y_test)
```
