### ISSUE TITLE
How to use it on RGB data

### ISSUE THREAD

**Issue by momo1986** [XifengGuo/CapsNet-Keras#90]
Hello, Guo.
I have tried the data in my RGB data.
However, the problem always exists:

Traceback (most recent call last):
  File "capsulenet-multi-gpu.py", line 166, in <module>
    multi_model.fit_generator(trainData, steps_per_epoch = 100, epochs = args.epochs, validation_data = validateData, validation_steps=100, callbacks = [log, tb, lr_decay])
  File "/root/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training_utils.py", line 101, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[0.41060576, 0.40476605, 0.47026658],
         [0.593203  , 0.5895052 , 0.6516646 ],
         [0.40907526, 0.4112418 , 0.47497278],
         ...,
         [0.52427757, 0.530366  , 0.59424573...

My specified KerasCapsNet is ：
       model, eval_model, manipulate_model = CapsNet(input_shape=(64, 64, 3),
                                                      n_class=10,
                                                      routings=args.routings)

Thanks for tolerance of disturbing

**Comment by XifengGuo** [comment]
@momo1986
I believe your `trainData` is not defined correctly. Please follow the format of the output of my `train_generator`.

**Comment by TolerantChief** [comment]
Hi @momo1986, did you find a solution to your problem? I'm stuck with the same error.
